spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
#    url: jdbc:mysql://mysql-container:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://host.docker.internal:3306/mydb?useSSL=false
    username: root
    password: 2111Hush
  jpa:
    show-sql: true 
    
server:
  servlet:
    contextPath: /productapi 
    
#swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swaggerui
